[build]
  command = "env"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.branch-deploy]
  command = "env"
  publish = ".next"
[context.branch-deploy.environment]
  SANITY_AUTH_PROJECT_ID = "ug4lbt5r"
  SANITY_AUTH_DATASET = "production"
  SANITY_AUTH_API_TOKEN = "SANITYAUTHTOKEN"
  SANITY_API_TOKEN = "SANITYAPITOKEN"
  GITHUB_ACCESS_TOKEN = "GITHUBTOKEN"
  NETLIFY_ACCESS_TOKEN = "NETLIFYTOKEN"
